# Generated by Django 5.2.8 on 2025-11-23 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('size', models.FloatField(help_text='Farm size in hectares')),
                ('crop_type', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm_profiles',
                'ordering': ['owner__username'],
            },
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='agriculture_app.farmprofile')),
            ],
            options={
                'db_table': 'field_plots',
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(choices=[('HIGH_MOISTURE', 'High Moisture'), ('LOW_MOISTURE', 'Low Moisture'), ('HIGH_TEMPERATURE', 'High Temperature'), ('LOW_TEMPERATURE', 'Low Temperature'), ('HIGH_HUMIDITY', 'High Humidity'), ('LOW_HUMIDITY', 'Low Humidity')], max_length=50)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('model_confidence', models.FloatField(help_text='0 to 1')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='agriculture_app.fieldplot')),
            ],
            options={
                'db_table': 'anomaly_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_type', models.CharField(choices=[('MOISTURE', 'Moisture'), ('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity')], max_length=20)),
                ('value', models.FloatField()),
                ('source', models.CharField(default='sensor', max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agriculture_app.fieldplot')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.CharField(max_length=255)),
                ('explanation_text', models.TextField()),
                ('confidence', models.FloatField(help_text='0 to 1')),
                ('anomaly_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='agriculture_app.anomalyevent')),
            ],
            options={
                'db_table': 'agent_recommendations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['anomaly_event'], name='agent_recom_anomaly_6ca0a7_idx'), models.Index(fields=['timestamp'], name='agent_recom_timesta_65e6cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='farmprofile',
            index=models.Index(fields=['owner'], name='farm_profil_owner_i_932979_idx'),
        ),
        migrations.AddIndex(
            model_name='farmprofile',
            index=models.Index(fields=['location'], name='farm_profil_locatio_055c39_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldplot',
            index=models.Index(fields=['farm'], name='field_plots_farm_id_fcc87d_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldplot',
            index=models.Index(fields=['name'], name='field_plots_name_792df0_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['plot'], name='anomaly_eve_plot_id_d1147a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['anomaly_type'], name='anomaly_eve_anomaly_7a3fba_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['severity'], name='anomaly_eve_severit_ca070e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['plot'], name='sensor_read_plot_id_fa4782_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor_type'], name='sensor_read_sensor__d7697b_idx'),
        ),
    ]
