# Generated by Django 6.0 on 2025-12-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentrecommendation',
            name='agent_recom_timesta_65e6cf_idx',
        ),
        migrations.AlterField(
            model_name='agentrecommendation',
            name='anomaly_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='agriculture_app.anomalyevent'),
        ),
        migrations.AlterField(
            model_name='agentrecommendation',
            name='confidence',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='agentrecommendation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='anomalyevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
