# Generated by Django 6.0 on 2025-12-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_app', '0002_remove_agentrecommendation_agent_recom_timesta_65e6cf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrecommendation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anomalyevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
