# Generated by Django 6.0 on 2025-12-11 20:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_app', '0003_alter_agentrecommendation_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrecommendation',
            options={'ordering': ['-simulated_time']},
        ),
        migrations.AlterModelOptions(
            name='anomalyevent',
            options={'ordering': ['-simulated_time']},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-simulated_time']},
        ),
        migrations.AddField(
            model_name='agentrecommendation',
            name='simulated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='simulated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='simulated_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 11, 20, 19, 31, 734074, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='agentrecommendation',
            index=models.Index(fields=['simulated_time'], name='agent_recom_simulat_a41562_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['simulated_time'], name='anomaly_eve_simulat_f81a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['simulated_time'], name='sensor_read_simulat_f1c6da_idx'),
        ),
    ]
